// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace UrlShortener.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260811153021_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.10")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("UrlShortener.Domain.Entities.ShortUrl", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier");

            b.Property<long>("ClickCount")
                .ValueGeneratedOnAdd()
                .HasColumnType("bigint")
                .HasDefaultValue(0L);

            b.Property<DateTime>("CreatedAtUtc").HasColumnType("datetime2");
            b.Property<DateTime?>("DeletedAtUtc").HasColumnType("datetime2");
            b.Property<DateTime?>("ExpiresAtUtc").HasColumnType("datetime2");

            b.Property<bool>("IsActive")
                .ValueGeneratedOnAdd()
                .HasColumnType("bit")
                .HasDefaultValue(true);

            b.Property<bool>("IsDeleted")
                .ValueGeneratedOnAdd()
                .HasColumnType("bit")
                .HasDefaultValue(false);

            b.Property<DateTime?>("LastAccessedAtUtc").HasColumnType("datetime2");

            b.Property<string>("OriginalUrl")
                .IsRequired()
                .HasMaxLength(2048)
                .HasColumnType("nvarchar(2048)");

            b.Property<string>("ShortCode")
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnType("nvarchar(20)")
                .UseCollation("Latin1_General_CS_AS");

            b.HasKey("Id");
            b.HasIndex("ExpiresAtUtc");
            b.HasIndex("IsDeleted");
            b.HasIndex("ShortCode").IsUnique();
            b.ToTable("ShortUrls", (string)null);
        });

        modelBuilder.Entity("UrlShortener.Domain.Entities.ShortUrlAccessLog", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier");

            b.Property<DateTime>("AccessedAtUtc").HasColumnType("datetime2");
            b.Property<string>("IpAddress").HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<string>("Referer").HasMaxLength(512).HasColumnType("nvarchar(512)");
            b.Property<Guid>("ShortUrlId").HasColumnType("uniqueidentifier");
            b.Property<string>("UserAgent").HasMaxLength(256).HasColumnType("nvarchar(256)");

            b.HasKey("Id");
            b.HasIndex("ShortUrlId", "AccessedAtUtc");
            b.ToTable("ShortUrlAccessLogs", (string)null);
        });

        modelBuilder.Entity("UrlShortener.Domain.Entities.ShortUrlAccessLog", b =>
        {
            b.HasOne("UrlShortener.Domain.Entities.ShortUrl", "ShortUrl")
                .WithMany("AccessLogs")
                .HasForeignKey("ShortUrlId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("ShortUrl");
        });

        modelBuilder.Entity("UrlShortener.Domain.Entities.ShortUrl", b =>
        {
            b.Navigation("AccessLogs");
        });
#pragma warning restore 612, 618
    }
}
